{{- if not .Values.rabbitmq.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.auth.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  managementEndpointsJson: {{ .Values.rabbitmq.auth.managementEndpoints | toJson | b64enc | quote }}
{{- end }}
